TestConfig:
  Name: aptos-localnet
  Experiments: 3
  Iterations: 10
  WaitDuration: 100
  StartupDuration: 1

SchedulerConfig:
  Type: "pct"
  Steps: 50
  Seed: 42
  Params: {"client_request_probability": 0.01, "d": 2}

NetworkConfig:
  BaseReplicaPort: 8000
  BaseInterceptorPort: 10000
  Protocol: "tcp"
  MessageType: TCP

FaultConfig:
  Faults: []

ProcessConfig:
  NumReplicas: 4
  Timeout: 100
  OutputDir:  output/aptos/20260216_145351
  ReplicaScript: aptos/aptos_server.sh
  ClientScripts: []
  CleanScript: aptos/aptos_clean.sh
  ReplicaParams:
    - "0 /tmp/aptos-dstest"
    - "1 /tmp/aptos-dstest"
    - "2 /tmp/aptos-dstest"
    - "3 /tmp/aptos-dstest"
